### ISSUE TITLE
SPS_HOME environment variable

### ISSUE THREAD

**Issue by olivialynn** [LSSTDESC/rail_fsps#8]
I'm trying to run the example notebook but running into 
`RuntimeError: You need to have the SPS_HOME environment variable`
after the first cell.

The only mentions I find of SPS_HOME is:
1. our `main.yml` workflow, where we set `export SPS_HOME="/opt/hostedtoolcache/Python/fsps"`
2. `test_sed_generator.py`, which runs 
    ```python
    if "SPS_HOME" not in os.environ:
        os.environ["SPS_HOME"] = "/opt/hostedtoolcache/Python/fsps"
    ```

Would be nice to avoid the user needing to set this manually in their shell (or at least, document how we'd like them to set it).

I'm looking into how we handle `RAILDIR` to see if we can copy that.

**Comment by torluca** [comment]
Hi Olivia, I'll add a line explaining how to do that in the demo notebook, but best is that the user does it itself.
